extends: ["stylelint-config-standard", "stylelint-prettier/recommended"]
rules:
  {
    "prettier/prettier": true,
    "font-family-no-missing-generic-family-keyword":
      [true, { "ignoreFontFamilies": ["StratosSkyeng"] }],
  }
